import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>bitbybit.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name='keywords' content='next, progamming, blog, bitbybit' />
      </Head>
      <main className={styles.main}>

        <div className={styles.navbar}>
          <Link href='/'><h1> bitbybit.com</h1></Link>
          <ul >
            <Link href='/'><li className="navlinks">Home</li> </Link>
            <Link href='/about'><li className="navlinks">About</li> </Link>
            <Link href='/contact'><li className="navlinks">contact</li> </Link>
            <Link href='/pro'><li className="navlinks">pro</li> </Link>
          </ul>
        </div>
        <div className={styles.description}>
          <a href='#'>the home of most simplified tech</a>
        </div>


        <div>
          list of blogs

        </div>

        <div >
        </div>
      </main>
    </>
  )
}
